import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams, useSearchParams } from "react-router-dom";
import {
  Activity,
  ArrowRight,
  Calendar,
  CheckCircle2,
  ExternalLink,
  Github,
  GitFork,
  Link2,
  Loader2,
  RefreshCw,
  Share2,
  Sparkles,
  Star,
  Twitter,
  Users
} from "lucide-react";
import "./styles.css";
import { fetchExploreStories, fetchStory } from "./utils/api";


function cx(...classes) {
  return classes.filter(Boolean).join(" ");
}

function useReveal(refreshKey) {
  useEffect(() => {
    const items = document.querySelectorAll("[data-reveal]");
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add("is-visible");
        });
      },
      { threshold: 0.18 }
    );
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, [refreshKey]);
}


function timeAgo(date) {
  const seconds = Math.max(1, Math.floor((Date.now() - new Date(date).getTime()) / 1000));
  const units = [
    ["y", 31536000],
    ["mo", 2592000],
    ["d", 86400],
    ["h", 3600],
    ["m", 60]
  ];
  for (const [label, size] of units) {
    const value = Math.floor(seconds / size);
    if (value >= 1) return `${value}${label} ago`;
  }
  return "just now";
}

function updateMeta(storyData) {
  const profile = storyData.github.profile;
  const title = `${profile.name || profile.login}'s GitStory`;
  const description = storyData.story.headline;
  document.title = title;

  const tags = {
    "og:title": title,
    "og:description": description,
    "og:image": profile.avatar_url
  };

  for (const [property, content] of Object.entries(tags)) {
    let tag = document.querySelector(`meta[property="${property}"]`);
    if (!tag) {
      tag = document.createElement("meta");
      tag.setAttribute("property", property);
      document.head.appendChild(tag);
    }
    tag.setAttribute("content", content);
  }
}

function Footer() {
  return <footer className="border-t border-white/10 py-8" />;
}

function LandingPage() {
  const [username, setUsername] = useState("");
  const [storyCount, setStoryCount] = useState(0);
  const navigate = useNavigate();

  useEffect(() => {
    let cancelled = false;
    fetchExploreStories()
      .then((stories) => {
        if (!cancelled) setStoryCount(stories.length);
      })
      .catch(() => {
        if (!cancelled) setStoryCount(0);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  function submit(event) {
    event.preventDefault();
    const clean = username.trim().replace(/^@/, "");
    if (clean) navigate(`/loading/${clean}`);
  }

  return (
    <main className="min-h-screen bg-github text-white">
      <section className="hero-grid flex min-h-[calc(100vh-84px)] items-center px-5 pb-24 pt-16">
        <div className="mx-auto flex w-full max-w-5xl flex-col items-center text-center">
          <div className="mb-9 inline-flex items-center gap-2 rounded-full bg-slate-800/90 px-4 py-2 text-sm text-slate-100 shadow-2xl backdrop-blur">
            <Github size={16} /> GitStory
          </div>
          <h1 className="max-w-4xl text-5xl font-black leading-[1.02] tracking-normal text-white sm:text-6xl lg:text-[72px]">
            Your GitHub has a story. <span className="text-orange">Let's tell it.</span>
          </h1>
          <p className="mt-8 max-w-2xl text-lg leading-8 text-slate-400 sm:text-[21px]">
            Turn your commit history, repositories, and late-night coding sessions into a beautiful, cinematic career
            narrative generated by AI.
          </p>

          <form
            onSubmit={submit}
            className="mt-10 flex w-full max-w-[448px] items-center gap-3 rounded-2xl border border-slate-700 bg-slate-950/70 p-2 shadow-[0_0_0_1px_rgba(148,163,184,0.08)] backdrop-blur"
          >
            <Github className="ml-3 shrink-0 text-slate-500" size={20} />
            <input
              value={username}
              onChange={(event) => setUsername(event.target.value)}
              placeholder="Enter GitHub username"
              className="min-w-0 flex-1 bg-transparent px-1 py-3 text-slate-100 outline-none placeholder:text-slate-500"
              aria-label="GitHub username"
            />
            <button className="inline-flex shrink-0 items-center gap-3 rounded-xl bg-orange px-4 py-3 text-sm font-bold text-white transition hover:bg-orange/90">
              Generate <ArrowRight size={16} />
            </button>
          </form>

          <div className="mt-8 flex flex-wrap items-center justify-center gap-6 text-sm text-slate-400">
            <Link className="inline-flex items-center gap-2 transition hover:text-orange" to="/story/sairam3824">
              <Sparkles size={16} /> See an example story
            </Link>
            <Link className="inline-flex items-center gap-2 transition hover:text-orange" to="/explore">
              <ArrowRight size={16} /> Explore all stories
            </Link>
          </div>

          <div className="mt-9 flex items-center justify-center gap-2 text-sm text-slate-400">
            <Users size={16} className="text-orange" />
            <strong className="text-white">{storyCount}</strong>
            <span>{storyCount === 1 ? "story generated so far" : "stories generated so far"}</span>
            <span className="text-orange">•</span>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}

function CompactGenerateForm() {
  const [username, setUsername] = useState("");
  const navigate = useNavigate();

  function submit(event) {
    event.preventDefault();
    const clean = username.trim().replace(/^@/, "");
    if (clean) navigate(`/loading/${clean}`);
  }

  return (
    <form onSubmit={submit} className="flex w-full items-center gap-2 sm:w-auto">
      <div className="flex min-w-0 flex-1 items-center gap-2 rounded-lg border border-slate-700 bg-white/[0.06] px-3 py-2 sm:w-64">
        <Github size={16} className="shrink-0 text-slate-400" />
        <input
          value={username}
          onChange={(event) => setUsername(event.target.value)}
          placeholder="Enter GitHub username"
          className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-slate-400"
          aria-label="GitHub username"
        />
      </div>
      <button className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-orange px-4 py-2 text-sm font-bold text-white transition hover:bg-orange/90">
        Generate <ArrowRight size={15} />
      </button>
    </form>
  );
}

function ExploreCard({ story }) {
  const shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(`Check out @${story.username}'s GitStory`)}&url=${encodeURIComponent(`${window.location.origin}/story/${story.username}`)}`;

  return (
    <article className="explore-card flex min-h-[360px] flex-col rounded-2xl border border-white/15 bg-[#202328] p-6 text-left shadow-[0_18px_50px_rgba(0,0,0,0.18)] transition hover:-translate-y-0.5 hover:border-orange/45">
      <Link to={`/story/${story.username}`} className="flex items-center gap-4">
        <img src={story.avatar} alt={`${story.username} avatar`} className="h-14 w-14 rounded-full border border-white/20 bg-slate-800 object-cover" />
        <div className="min-w-0">
          <h3 className="truncate text-lg font-black text-white">@{story.username}</h3>
          <p className="text-sm text-slate-400">{timeAgo(story.generatedAt)}</p>
        </div>
      </Link>

      <div className="mt-5">
        <span className="rounded-md border border-orange/40 bg-orange/10 px-3 py-1 text-sm font-bold text-orange">{story.type}</span>
      </div>

      <p className="mt-5 min-h-[72px] text-[15px] leading-6 text-slate-200">{story.headline}</p>

      <div className="mt-4 flex min-h-[56px] flex-wrap content-start gap-2">
        {story.tags.map((tag) => (
          <span key={tag} className="rounded border border-white/15 bg-white/[0.07] px-2.5 py-1 font-mono text-xs text-slate-300">
            {tag}
          </span>
        ))}
      </div>

      <div className="mt-auto border-t border-white/10 pt-3">
        <div className="flex items-center gap-5 text-sm text-slate-400">
          <span className="inline-flex items-center gap-1"><Star size={14} /> {story.stars}</span>
          <span className="inline-flex items-center gap-1"><GitFork size={14} /> {story.repos}</span>
          <span className="inline-flex items-center gap-1"><Users size={14} /> {story.followers}</span>
        </div>
        <a
          href={shareUrl}
          className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg border border-white/15 px-4 py-2 text-sm text-slate-400 transition hover:border-orange/50 hover:text-orange"
        >
          <Twitter size={14} /> Share on X
        </a>
      </div>
    </article>
  );
}

function ExplorePage() {
  const [stories, setStories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    document.title = "Explore GitStories";
    let cancelled = false;
    fetchExploreStories()
      .then((items) => {
        if (!cancelled) setStories(items);
      })
      .catch((err) => {
        if (!cancelled) setError(err.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main className="min-h-screen bg-github text-white">
      <header className="sticky top-0 z-40 border-b border-white/10 bg-[#0b1017]/95 px-5 py-4 backdrop-blur">
        <div className="mx-auto flex max-w-[1880px] flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <Link to="/" className="inline-flex items-center gap-3 text-xl font-black text-white">
            <Github size={22} /> GitStory
          </Link>
          <CompactGenerateForm />
        </div>
      </header>

      <section className="mx-auto max-w-6xl px-5 pb-12 pt-8 text-center sm:pt-12">
        <div className="inline-flex items-center gap-2 rounded-full border border-orange/35 bg-orange/10 px-4 py-2 text-sm font-bold text-orange">
          <Sparkles size={15} /> Developer Stories
        </div>
        <h1 className="mt-7 text-5xl font-black leading-tight tracking-normal text-white sm:text-6xl">Explore GitStories</h1>
        <p className="mx-auto mt-4 max-w-2xl text-xl leading-8 text-slate-400">
          Every GitHub profile hides a unique story. Discover the builders, experimenters, and creators who've
          generated theirs.
        </p>
      </section>

      {loading && (
        <section className="mx-auto max-w-3xl px-5 py-20 text-center text-slate-400">
          <Loader2 className="mx-auto animate-spin text-orange" size={32} />
          <p className="mt-4">Loading generated stories...</p>
        </section>
      )}

      {!loading && error && (
        <section className="mx-auto max-w-3xl px-5 py-20 text-center text-slate-400">
          <p>{error}</p>
        </section>
      )}

      {!loading && !error && stories.length === 0 && (
        <section className="mx-auto max-w-3xl px-5 py-20 text-center">
          <div className="rounded-2xl border border-white/10 bg-[#202328] p-10">
            <Github className="mx-auto text-orange" size={38} />
            <h2 className="mt-5 text-3xl font-black text-white">No GitStories yet</h2>
            <p className="mx-auto mt-3 max-w-xl text-slate-400">
              Enter a GitHub username and generate a story. Once it is created, it will appear here automatically.
            </p>
          </div>
        </section>
      )}

      {!loading && !error && stories.length > 0 && (
        <section className="mx-auto grid max-w-[1210px] grid-cols-1 gap-4 px-5 pb-20 sm:grid-cols-2 lg:grid-cols-4">
          {stories.map((story) => (
            <ExploreCard key={story.username} story={story} />
          ))}
        </section>
      )}
    </main>
  );
}

function LoadingPage() {
  const { username } = useParams();
  const navigate = useNavigate();
  const [active, setActive] = useState(0);
  const steps = useMemo(
    () => [
      ["Fetching your repos...", 1500],
      ["Analyzing your journey...", 1500],
      ["Crafting your story...", 2000],
      ["Designing your page...", 1000]
    ],
    []
  );

  useEffect(() => {
    let total = 0;
    const timers = steps.map(([, delay], index) => {
      total += delay;
      return setTimeout(() => setActive(index + 1), total);
    });
    const done = setTimeout(() => navigate(`/story/${username}`), total + 250);
    return () => [...timers, done].forEach(clearTimeout);
  }, [navigate, steps, username]);

  return (
    <main className="hero-grid flex min-h-screen items-center justify-center bg-github px-5 text-white">
      <div className="w-full max-w-xl text-center">
        <div className="mx-auto mb-8 flex h-20 w-20 items-center justify-center rounded-full border border-orange/40 bg-orange/10 shadow-glow">
          <Loader2 className="animate-spin text-orange" size={34} />
        </div>
        <h1 className="text-4xl font-black">Your GitHub is being turned into a legend.</h1>
        <div className="mt-10 space-y-4 text-left">
          {steps.map(([label], index) => (
            <div
              key={label}
              className={cx(
                "flex items-center gap-3 rounded-lg border p-4 transition",
                index < active
                  ? "border-orange/50 bg-orange/10 text-white"
                  : index === active
                    ? "border-white/15 bg-white/[0.06] text-slate-200"
                    : "border-white/10 bg-white/[0.03] text-slate-500"
              )}
            >
              {index < active ? <CheckCircle2 className="text-orange" size={20} /> : <Loader2 className={index === active ? "animate-spin text-orange" : ""} size={20} />}
              <span className="font-medium">{label}</span>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}

function ErrorState({ message }) {
  return (
    <main className="hero-grid flex min-h-screen items-center justify-center bg-github px-5 text-white">
      <div className="max-w-lg text-center">
        <Github className="mx-auto text-orange" size={48} />
        <h1 className="mt-6 text-4xl font-black">We couldn't find that GitHub story.</h1>
        <p className="mt-4 text-slate-400">{message} Try checking the spelling, removing the @, or using a public profile.</p>
        <Link className="mt-8 inline-flex rounded-xl bg-orange px-5 py-3 font-bold text-white" to="/">
          Try another username
        </Link>
      </div>
    </main>
  );
}

function formatMonthYear(date) {
  if (!date) return "Now";
  return new Date(date).toLocaleDateString(undefined, { month: "short", year: "numeric" });
}

function StoryPage() {
  const { username } = useParams();
  const [searchParams, setSearchParams] = useSearchParams();
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState("");
  const regenerate = searchParams.get("regenerate") === "1";
  const effectiveUsername = username;

  useReveal(`${loading}:${data?.username ?? ""}`);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError("");
    fetchStory(effectiveUsername, regenerate)
      .then((story) => {
        if (cancelled) return;
        setData(story);
        updateMeta(story);
      })
      .catch((err) => {
        if (!cancelled) setError(err.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [effectiveUsername, regenerate]);

  async function copyUrl() {
    await navigator.clipboard.writeText(window.location.href.replace("?regenerate=1", ""));
    setToast("Link copied!");
    setTimeout(() => setToast(""), 2200);
  }

  function refresh() {
    setSearchParams({ regenerate: "1", t: Date.now().toString() });
  }

  if (loading) return <LoadingPage />;
  if (error) return <ErrorState message={error} />;

  const { github, story } = data;
  const { profile, computed } = github;
  const maxLanguage = Math.max(...computed.top_languages.map((language) => language.count), 1);
  const generatedLabel = data.cached ? "cached" : `${data.generatedInSeconds}s`;
  const shareOnX = `https://twitter.com/intent/tweet?text=${encodeURIComponent(`Read @${profile.login}'s GitStory`)}&url=${encodeURIComponent(window.location.href.replace("?regenerate=1", ""))}`;
  const statInsights = new Map(story.fun_stats.map((stat) => [stat.label.toLowerCase(), stat.insight]));
  const numberCards = [
    {
      value: computed.total_stars.toLocaleString(),
      label: "Stars Earned",
      insight: statInsights.get("stars") || "Every star is a quiet signal that the work is finding its people."
    },
    {
      value: profile.public_repos.toLocaleString(),
      label: "Repos Built",
      insight: statInsights.get("repos") || "A public trail of ideas that moved from intention into code."
    },
    {
      value: computed.years_on_github.toLocaleString(),
      label: "Years Coding",
      insight: statInsights.get("years") || "Enough time for experiments to become taste, momentum, and craft."
    },
    {
      value: profile.followers.toLocaleString(),
      label: "Followers",
      insight: statInsights.get("followers") || "A small circle of people paying attention to what comes next."
    }
  ];

  return (
    <main className="min-h-screen bg-github text-slate-200">
      {toast && <div className="fixed right-5 top-5 z-50 rounded-xl border border-orange/40 bg-slate-950 px-4 py-3 text-sm font-bold text-orange shadow-glow">{toast}</div>}

      <header className="sticky top-0 z-40 border-b border-white/10 bg-[#120f16]/95 px-5 py-4 backdrop-blur">
        <div className="mx-auto flex max-w-[1880px] flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <Link to="/" className="inline-flex items-center gap-3 text-xl font-black text-white">
            <Github size={22} /> GitStory
          </Link>
          <div className="flex flex-wrap items-center gap-3 text-sm">
            <span className="font-mono text-slate-500">Generated in {generatedLabel}</span>
            <button onClick={copyUrl} className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-4 py-2 font-bold text-white transition hover:border-orange/60 hover:text-orange">
              <Link2 size={16} /> Copy Link
            </button>
            <button onClick={refresh} className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-4 py-2 font-bold text-white transition hover:border-orange/60 hover:text-orange">
              <RefreshCw size={16} /> Regenerate
            </button>
          </div>
        </div>
      </header>

      <section className="story-hero px-5 pb-24 pt-20 text-center">
        <div className="mx-auto flex max-w-5xl flex-col items-center">
          <img
            src={profile.avatar_url}
            alt={`${profile.login} avatar`}
            className="h-40 w-40 rounded-full border-4 border-[#080b11] object-cover shadow-[0_0_48px_rgba(249,115,22,0.7)] sm:h-48 sm:w-48"
          />
          <div className="mt-10 inline-flex rounded-md border border-orange/50 bg-orange/20 px-5 py-2 text-sm font-black text-orange">{story.builder_type}</div>
          <h1 className="mx-auto mt-10 max-w-5xl text-5xl font-black leading-[1.18] tracking-normal text-white sm:text-7xl lg:text-[82px]">
            {story.headline}
          </h1>
          <p className="mt-9 font-mono text-2xl text-slate-400">@{profile.login}</p>

          <div className="mt-12 grid w-full max-w-4xl grid-cols-2 rounded-2xl border border-white/15 bg-[#202328] px-6 py-7 shadow-2xl sm:grid-cols-4">
            {[
              [Activity, "Repos", profile.public_repos],
              [Star, "Stars", computed.total_stars.toLocaleString()],
              [Users, "Followers", profile.followers.toLocaleString()],
              [Calendar, "Years", computed.years_on_github]
            ].map(([Icon, label, value]) => (
              <div key={label} className="py-3">
                <div className="inline-flex items-center gap-2 font-mono text-sm font-bold uppercase tracking-widest text-slate-400">
                  {React.createElement(Icon, { size: 16 })} {label}
                </div>
                <p className="mt-2 text-4xl font-black text-white">{value}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section data-reveal className="reveal border-t border-white/10 px-5 py-20">
        <div className="mx-auto max-w-4xl">
          <div className="mb-10 flex items-center gap-5">
            <div className="h-px flex-1 bg-orange/60" />
            <p className="font-mono text-sm font-bold uppercase tracking-[0.25em] text-orange">Chapter 0: The Beginning</p>
            <div className="h-px flex-1 bg-orange/60" />
          </div>
          <p className="story-serif text-center text-3xl leading-[1.45] text-white sm:text-4xl">{story.origin_story}</p>
          <a href={computed.first_repo?.html_url || profile.html_url} className="mt-14 flex flex-col gap-5 rounded-xl border border-white/15 bg-[#202328] p-6 transition hover:border-orange/55 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <span className="font-mono text-sm uppercase tracking-[0.18em] text-slate-400">First Public Repository</span>
              <h3 className="mt-2 inline-flex items-center gap-2 text-2xl font-black text-white">
                {computed.first_repo?.name || "First public step"} <ExternalLink size={18} className="text-slate-500" />
              </h3>
            </div>
            <span className="w-fit rounded-md bg-orange/20 px-4 py-2 font-mono text-sm font-bold text-orange">{formatMonthYear(computed.first_repo?.created_at)}</span>
          </a>
        </div>
      </section>

      <section data-reveal className="reveal border-t border-white/10 bg-[#080d12] px-5 py-24">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-4xl font-black text-white sm:text-5xl">Builder DNA</h2>
          <div className="mt-14 grid gap-12 lg:grid-cols-2 lg:items-center">
          <div>
            <div className="text-5xl text-orange/35">”</div>
            <blockquote className="story-serif border-l-2 border-orange pl-8 text-3xl italic leading-tight text-white">
              “{story.superpower}”
            </blockquote>
            <p className="mt-8 text-lg leading-8 text-slate-400">{story.builder_type_description}</p>
          </div>
          <div className="space-y-7">
            <p className="font-mono text-sm uppercase tracking-[0.18em] text-slate-400">Top Languages</p>
            {computed.top_languages.map((language) => (
              <div key={language.name}>
                <div className="mb-3 flex justify-between text-base">
                  <span className="font-bold text-white">{language.name}</span>
                  <span className="font-mono text-slate-400">{language.count} repos</span>
                </div>
                <div className="h-2.5 overflow-hidden rounded-full bg-white/15">
                  <div className="language-bar h-full rounded-full bg-orange" style={{ "--bar-width": `${(language.count / maxLanguage) * 100}%` }} />
                </div>
              </div>
            ))}
          </div>
          </div>
        </div>
      </section>

      <section data-reveal className="reveal border-t border-white/10 px-5 py-24">
        <h2 className="text-center text-4xl font-black text-white sm:text-5xl">The Journey</h2>
        <div className="story-timeline mx-auto mt-20 max-w-6xl">
          {story.chapter_titles.map((chapter, index) => (
            <article key={chapter.title} className={cx("story-timeline-item", index % 2 ? "story-timeline-right" : "story-timeline-left")}>
              <div className="story-timeline-card">
                <h3 className="text-2xl font-black leading-snug text-white">{chapter.title}</h3>
                <p className="mt-5 text-lg leading-8 text-slate-400">{chapter.description}</p>
              </div>
              <span className="story-timeline-dot">{index + 1}</span>
            </article>
          ))}
        </div>
      </section>

      <section data-reveal className="reveal bg-black/35 px-5 py-24">
        <div className="mx-auto max-w-6xl">
          <h2 className="text-center text-4xl font-black text-white sm:text-5xl">By The Numbers</h2>
          <div className="mt-16 grid gap-7 sm:grid-cols-2">
          {numberCards.map((stat) => (
            <article key={stat.label} className="group rounded-xl border border-white/15 bg-white/[0.035] p-10 text-center transition hover:-translate-y-0.5 hover:border-orange/70">
              <p className="text-6xl font-black text-white transition group-hover:text-orange">{stat.value}</p>
              <p className="mt-3 font-mono text-sm uppercase tracking-[0.18em] text-slate-400">{stat.label}</p>
              <p className="story-serif mx-auto mt-6 max-w-md text-lg italic leading-7 text-orange">"{stat.insight}"</p>
            </article>
          ))}
          </div>
        </div>
      </section>

      <section data-reveal className="reveal border-t border-white/10 bg-[#0d1117] px-5 py-24">
        <div className="mx-auto max-w-6xl">
        <h2 className="text-center text-4xl font-black text-white sm:text-5xl">Key Projects</h2>
        <div className="mt-16 grid gap-7 lg:grid-cols-2">
          {computed.top_repos.map((repo) => (
            <article key={repo.name} className="rounded-xl border border-white/15 bg-[#202328] p-8 transition hover:-translate-y-0.5 hover:border-orange/55">
              <div className="flex items-start justify-between gap-4">
                <h3 className="text-2xl font-black text-white">{repo.name}</h3>
                <span className="inline-flex items-center gap-1 rounded-md bg-white/[0.06] px-3 py-2 text-slate-400">
                  <Star size={16} /> {repo.stargazers_count.toLocaleString()}
                </span>
              </div>
              <p className="mt-7 min-h-14 text-lg leading-8 text-slate-400">{repo.description || "No description provided."}</p>
              <div className="mt-8 flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-3 text-sm text-slate-400">
                  {repo.language && <span className="rounded border border-white/15 bg-white/[0.06] px-3 py-1 font-mono">{repo.language}</span>}
                  <span className="inline-flex items-center gap-1"><GitFork size={14} /> {repo.forks_count}</span>
                </div>
                <a href={repo.html_url} className="inline-flex items-center gap-2 text-sm font-bold text-orange hover:text-orange/80">
                  View on GitHub <ExternalLink size={15} />
                </a>
              </div>
            </article>
          ))}
        </div>
        </div>
      </section>

      <section className="story-legacy border-y border-white/10 px-5 py-28 text-center">
        <p className="mx-auto max-w-6xl text-4xl font-black leading-tight text-white sm:text-6xl">
          {story.legacy_statement}
        </p>
      </section>

      <section className="px-5 py-24 text-center">
        <p className="mx-auto max-w-3xl text-2xl leading-10 text-slate-400">{story.cta_message}</p>
        <div className="mt-10 flex flex-wrap justify-center gap-4">
          <button onClick={copyUrl} className="inline-flex items-center gap-3 rounded-full bg-orange px-8 py-4 text-lg font-black text-white shadow-[0_0_32px_rgba(249,115,22,0.45)] transition hover:bg-orange/90">
            <Share2 size={20} /> Copy Link
          </button>
          <a href={shareOnX} className="inline-flex items-center gap-3 rounded-full border border-white/20 bg-black px-8 py-4 text-lg font-black text-white transition hover:border-orange/60 hover:text-orange">
            <Twitter size={20} /> Share on X
          </a>
          <Link to="/" className="inline-flex items-center gap-3 rounded-full border border-white/20 px-8 py-4 text-lg font-black text-white transition hover:border-orange/60 hover:text-orange">
            Generate for a Friend
          </Link>
        </div>
        <div className="mt-12">
          <a href={profile.html_url} className="inline-flex items-center gap-2 text-slate-400 transition hover:text-orange">
            <Github size={18} /> Follow @{profile.login} on GitHub
          </a>
        </div>
      </section>

      <Footer />
    </main>
  );
}

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<LandingPage />} />
        <Route path="/explore" element={<ExplorePage />} />
        <Route path="/loading/:username" element={<LoadingPage />} />
        <Route path="/story/:username" element={<StoryPage />} />
      </Routes>
    </BrowserRouter>
  );
}

createRoot(document.getElementById("root")).render(<App />);
